site_name: A unified Vision-Language Model (VLM) Pipeline documentation
site_url: https://username.github.io/univlm
theme:
  name: dracula
  navigation:
    - Home: docs/home.md
    - Requirements & Installation: docs/requirements.md
    - Quickstart: docs/quickstart.md
    - Other thing: docs/other.md
    - About: docs/about.md


